name: Monitor Spreads

on:
  schedule:
    - cron: '*/15 * * * *'  # Ejecuta cada 15 minutos (UTC)
  workflow_dispatch:        # Permite ejecución manual desde GitHub

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monitor_spreads
        env:
          TRADIER_API_KEY: ${{ secrets.TRADIER_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python monitor_worker/monitor_spreads.py
